llm:
  provider: "openrouter"
  model: "deepseek/deepseek-r1:free"
  temperature: 0.7
  max_tokens: 1024

agents:
  searcher: true

  summarizer:
    model: "moonshotai/kimi-k2:free"
    temperature: 0.85
    max_tokens: 1024

  factchecker:
    model: "deepseek/deepseek-r1:free"
    temperature: 0.4
    max_tokens: 512

  evaluator:
    model: "google/gemma-3-4b-it:free"
    temperature: 0.5
    max_tokens: 768

tools:
  web_search: "serper"  # upgraded from duckduckgo
  knowledge_base: "wikipedia"
